# Generated by Django 6.0.8 on 2026-09-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_contactevent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyproductstats',
            name='unique_product_day',
        ),
        migrations.DeleteModel(
            name='DailyProductStats',
        ),
    ]
