# Generated by Django 6.0.8 on 2026-09-23 01:36

import apps.live.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_productimage_master_categoryattribute_favorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('live', 'En direct'), ('ended', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.live.models.live_thumbnail_upload_to)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='programmé pour')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_viewers', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=40, verbose_name='fournisseur vidéo')),
                ('provider_session_id', models.CharField(blank=True, max_length=255)),
                ('playback_url', models.URLField(blank=True)),
                ('ingest_url', models.URLField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session live',
                'verbose_name_plural': 'sessions live',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_appearances', to='catalog.product')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_products', to='live.livesession')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_messages', to='catalog.product')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_messages', to=settings.AUTH_USER_MODEL)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.livesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='live.livesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'started_at'], name='live_livese_status_c9e48b_idx'),
        ),
        migrations.AddConstraint(
            model_name='liveproduct',
            constraint=models.UniqueConstraint(fields=('live', 'product'), name='unique_product_per_live'),
        ),
        migrations.AddIndex(
            model_name='livemessage',
            index=models.Index(fields=['live', 'created_at'], name='live_liveme_live_id_ac027f_idx'),
        ),
        migrations.AddIndex(
            model_name='liveviewer',
            index=models.Index(fields=['live', 'left_at'], name='live_livevi_live_id_b09660_idx'),
        ),
    ]
