# Generated by Django 6.0.8 on 2026-09-23 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_message', 'Nouveau message'), ('new_product', 'Nouvelle annonce'), ('product_updated', 'Annonce mise à jour'), ('product_approved', 'Annonce approuvée'), ('product_rejected', 'Annonce rejetée'), ('favorite', 'Favori'), ('live_started', 'Live démarré'), ('system', 'Système')], default='system', max_length=32, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('url', models.CharField(blank=True, help_text='Chemin frontend ouvert au clic, ex : /compte/messages/12', max_length=255, verbose_name='lien')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
