# Generated by Django 6.0.8 on 2026-09-23 01:36

import apps.messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Durée du vocal en secondes.', verbose_name='durée (s)'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.messaging.models.message_audio_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('audio', 'Audio'), ('product', 'Annonce'), ('system', 'Système')], default='text', max_length=12, verbose_name='type'),
        ),
    ]
