# Generated by Django 6.0.8 on 2026-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_status_b4a4dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_categor_da0f0a_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Le fournisseur peut dépublier une annonce approuvée sans repasser par la modération.', verbose_name='visible'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active', 'listing_type', 'city'], name='catalog_pro_status_0a5b52_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', 'is_active'], name='catalog_pro_categor_edaf4b_idx'),
        ),
    ]
