# Generated by Django 6.0.8 on 2026-09-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_catalog_pro_status_b4a4dd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='Burkina Faso', max_length=120, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_precision',
            field=models.CharField(choices=[('exact', 'Position exacte'), ('approximate', 'Position approximative')], default='approximate', help_text="Le fournisseur choisit s'il expose la position exacte ou seulement la ville.", max_length=12, verbose_name='précision de la localisation'),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='product',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='place id (Google Maps)'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='région'),
        ),
    ]
