# Generated by Django 6.0.8 on 2026-09-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_country_product_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='partages'),
        ),
    ]
