# Generated by Django 6.0.8 on 2026-09-23 01:36

import apps.catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_shares_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='master',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.product_image_upload_to),
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=140, verbose_name='slug')),
                ('attribute_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('boolean', 'Oui / Non'), ('select', 'Liste déroulante'), ('multi_select', 'Choix multiples'), ('date', 'Date')], default='text', max_length=16, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='obligatoire')),
                ('filterable', models.BooleanField(default=False, verbose_name='filtrable')),
                ('searchable', models.BooleanField(default=False, verbose_name='recherchable')),
                ('unit', models.CharField(blank=True, help_text='Ex : km, m², ch', max_length=20, verbose_name='unité')),
                ('options', models.JSONField(blank=True, default=list, help_text='Valeurs possibles pour les types liste : ["Essence", "Diesel"]', verbose_name='options')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category')),
            ],
            options={
                'verbose_name': 'attribut de catégorie',
                'verbose_name_plural': 'attributs de catégorie',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='valeur')),
                ('numeric_value', models.FloatField(blank=True, db_index=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.categoryattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
            ],
            options={
                'verbose_name': "valeur d'attribut",
                'verbose_name_plural': "valeurs d'attribut",
            },
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_attribute_slug_per_category'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_per_user_product'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'numeric_value'], name='catalog_pro_attribu_5203cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='unique_value_per_product_attribute'),
        ),
    ]
