# Generated by Django 6.0.8 on 2026-09-15 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil fournisseur',
                'verbose_name_plural': 'profils fournisseurs',
            },
        ),
    ]
