# Generated by Django 6.0.8 on 2026-09-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='allow_whatsapp_contact',
            field=models.BooleanField(default=False, verbose_name='autoriser le contact WhatsApp'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Optionnel. Requis pour activer le contact WhatsApp.', max_length=20, verbose_name='numéro WhatsApp'),
        ),
    ]
