# Generated by Django 6.0.8 on 2026-09-24 12:32

import apps.media.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0002_message_audio_duration_message_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio')], max_length=8)),
                ('status', models.CharField(choices=[('uploading', 'Envoi'), ('processing', 'Traitement'), ('ready', 'Prêt'), ('failed', 'Échec')], default='processing', max_length=12)),
                ('file', models.FileField(upload_to=apps.media.models.attachment_upload_to)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=apps.media.models.poster_upload_to)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('size', models.PositiveBigIntegerField(default=0, help_text='Taille stockée, en octets.')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Secondes, audio et vidéo.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['message', 'position'], name='nogoya_medi_message_1004df_idx')],
            },
        ),
    ]
